"""add announcement table with priority

Revision ID: 3620d656ee10
Revises: 4ecea9d79c17
Create Date: 2026-05-10 22:38:10.451731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3620d656ee10'
down_revision = '4ecea9d79c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=False, server_default='info'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
