"""add profile fields to user

Revision ID: bc365bd0b9e9
Revises: f4e8d2c1a6b9
Create Date: 2026-05-22 18:50:47.355269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc365bd0b9e9'
down_revision = 'f4e8d2c1a6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('year_of_study', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('year_of_study')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
