"""add last_login_ip

Revision ID: df6168cfbe63
Revises: 286561cef2dc
Create Date: 2026-05-22 19:15:37.339414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6168cfbe63'
down_revision = '286561cef2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_ip')

    # ### end Alembic commands ###
